<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Cuco_GHome_api自动化测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">Cuco_GHome_api自动化测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> Cuco_Jan</p>
<p class='attribute'><strong>开始时间 : </strong> 2021-04-06 16:09:34</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:49.992581</p>
<p class='attribute'><strong>测试结果 : </strong> 共 43，失败 41，错误 2，通过率= 0.00%</p>

<p class='description'>用例执行情况</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 41 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 43 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>test_api.Test_api</td>
    <td class="text-center">43</td>
    <td class="text-center">0</td>
    <td class="text-center">41</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',43)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>失败</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696580737, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696582140, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696584223, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;："http_code": 400, "err_code": 10000, "success": false, "msg": "unknow error"
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696585329, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>失败</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696586560, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696587768, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696588954, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696589948, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696590924, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696591960, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_11' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_11</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_11'>失败</button>
    <div id='div_ft1_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_11'>失败</button>
    <div id='div_ft1_11' class="collapse in" align="left">
    <pre>
    
ft1_11: post请求body类型为： ,body内容为：{"ids": ["2f81870ea0df4bc8b1c4a5749d67130e"]}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696593055, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_12' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_12</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse in" align="left">
    <pre>
    
ft1_12: post请求body类型为： ,body内容为：{"ids": [""]}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696594298, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_13' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_13</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_13'>失败</button>
    <div id='div_ft1_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_13'>失败</button>
    <div id='div_ft1_13' class="collapse in" align="left">
    <pre>
    
ft1_13: post请求body类型为： ,body内容为：{"payload": {"switch": true}}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696595484, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_14' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_14</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse in" align="left">
    <pre>
    
ft1_14: post请求body类型为： ,body内容为：{"payload": {"switch": false}}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696597870, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_15' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_15</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_15'>失败</button>
    <div id='div_ft1_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_15'>失败</button>
    <div id='div_ft1_15' class="collapse in" align="left">
    <pre>
    
ft1_15: post请求body类型为： ,body内容为：{'timezoneId': 'Asia/Shanghai', 'pairType': 'EZ'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696599183, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_16' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_16</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse in" align="left">
    <pre>
    
ft1_16: post请求body类型为： ,body内容为：{'timezoneId': 'Asia/Shanghai', 'pairType': 'BLE'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696600512, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_17' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_17</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_17'>失败</button>
    <div id='div_ft1_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_17'>失败</button>
    <div id='div_ft1_17' class="collapse in" align="left">
    <pre>
    
ft1_17: post请求body类型为： ,body内容为：{'timezoneId': 'Asia/Shanghai', 'pairType': 'AP'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696601695, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_18' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_18'>失败</button>
    <div id='div_ft1_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_18'>失败</button>
    <div id='div_ft1_18' class="collapse in" align="left">
    <pre>
    
ft1_18: post请求body类型为： ,body内容为：{'timezoneId': 'Asia/Shanghai', 'pairType': 'AP'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696602799, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_19' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_19</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_19'>失败</button>
    <div id='div_ft1_19' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_19'>失败</button>
    <div id='div_ft1_19' class="collapse in" align="left">
    <pre>
    
ft1_19: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696603882, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_20' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_20</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_20'>失败</button>
    <div id='div_ft1_20' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_20'>失败</button>
    <div id='div_ft1_20' class="collapse in" align="left">
    <pre>
    
ft1_20: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696605231, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_21' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_21</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_21' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_21'>失败</button>
    <div id='div_ft1_21' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_21' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_21'>失败</button>
    <div id='div_ft1_21' class="collapse in" align="left">
    <pre>
    
ft1_21: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696606311, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_22' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_22</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_22'>失败</button>
    <div id='div_ft1_22' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_22'>失败</button>
    <div id='div_ft1_22' class="collapse in" align="left">
    <pre>
    
ft1_22: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 400, "err_code": 10023, "success": false, "msg": "Device name cannot be duplicated, please modify and try to save again",
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696607307, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_23' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_23</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_23' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_23'>失败</button>
    <div id='div_ft1_23' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_23' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_23'>失败</button>
    <div id='div_ft1_23' class="collapse in" align="left">
    <pre>
    
ft1_23: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 404, "err_code": 10000, "success": false,
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696608290, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_24' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_24</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_24'>失败</button>
    <div id='div_ft1_24' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_24'>失败</button>
    <div id='div_ft1_24' class="collapse in" align="left">
    <pre>
    
ft1_24: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696609264, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_25' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_25</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_25' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_25'>失败</button>
    <div id='div_ft1_25' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_25' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_25'>失败</button>
    <div id='div_ft1_25' class="collapse in" align="left">
    <pre>
    
ft1_25: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 400, "err_code": 90003, "success": false, "msg": "device data does not exist"
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696610215, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_26' class='none'>
    <td class='errorCase'><div class='testcase'>test_GHome_api_26</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_26'>错误</button>
    <div id='div_ft1_26' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_26'>错误</button>
    <div id='div_ft1_26' class="collapse in" align="left">
    <pre>
    
ft1_26: Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 48, in test_GHome_api
    base_api.wirte_result(res, filename=reportxlsx)
  File "D:\project\Ghome_api\common\base_api.py", line 103, in wirte_result
    row_nub = result['rowNum']
KeyError: 'rowNum'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_27' class='none'>
    <td class='errorCase'><div class='testcase'>test_GHome_api_27</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_27' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_27'>错误</button>
    <div id='div_ft1_27' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_27' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_27'>错误</button>
    <div id='div_ft1_27' class="collapse in" align="left">
    <pre>
    
ft1_27: Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 48, in test_GHome_api
    base_api.wirte_result(res, filename=reportxlsx)
  File "D:\project\Ghome_api\common\base_api.py", line 103, in wirte_result
    row_nub = result['rowNum']
KeyError: 'rowNum'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_28' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_28</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_28'>失败</button>
    <div id='div_ft1_28' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_28'>失败</button>
    <div id='div_ft1_28' class="collapse in" align="left">
    <pre>
    
ft1_28: post请求body类型为： ,body内容为：{}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696611241, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_29' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_29</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_29' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_29'>失败</button>
    <div id='div_ft1_29' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_29' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_29'>失败</button>
    <div id='div_ft1_29' class="collapse in" align="left">
    <pre>
    
ft1_29: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696612348, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_30' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_30</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_30'>失败</button>
    <div id='div_ft1_30' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_30'>失败</button>
    <div id='div_ft1_30' class="collapse in" align="left">
    <pre>
    
ft1_30: post请求body类型为： ,body内容为：{'roomName': 'Outside111'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696613355, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_31' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_31</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_31' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_31'>失败</button>
    <div id='div_ft1_31' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_31' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_31'>失败</button>
    <div id='div_ft1_31' class="collapse in" align="left">
    <pre>
    
ft1_31: post请求body类型为： ,body内容为：{'roomName': 'Outside111'}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 400, "err_code": 10022, "success": false, "msg": "Room name cannot be duplicated, please modify and try to save again"
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696614327, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_32' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_32</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_32'>失败</button>
    <div id='div_ft1_32' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_32'>失败</button>
    <div id='div_ft1_32' class="collapse in" align="left">
    <pre>
    
ft1_32: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696615327, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_33' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_33</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_33' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_33'>失败</button>
    <div id='div_ft1_33' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_33' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_33'>失败</button>
    <div id='div_ft1_33' class="collapse in" align="left">
    <pre>
    
ft1_33: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696615577, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_34' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_34</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_34' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_34'>失败</button>
    <div id='div_ft1_34' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_34' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_34'>失败</button>
    <div id='div_ft1_34' class="collapse in" align="left">
    <pre>
    
ft1_34: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696616545, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_35' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_35</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_35' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_35'>失败</button>
    <div id='div_ft1_35' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_35' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_35'>失败</button>
    <div id='div_ft1_35' class="collapse in" align="left">
    <pre>
    
ft1_35: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696617607, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_36' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_36</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_36' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_36'>失败</button>
    <div id='div_ft1_36' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_36' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_36'>失败</button>
    <div id='div_ft1_36' class="collapse in" align="left">
    <pre>
    
ft1_36: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696618896, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_37' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_37</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_37' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_37'>失败</button>
    <div id='div_ft1_37' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_37' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_37'>失败</button>
    <div id='div_ft1_37' class="collapse in" align="left">
    <pre>
    
ft1_37: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696620240, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_38' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_38</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_38' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_38'>失败</button>
    <div id='div_ft1_38' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_38' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_38'>失败</button>
    <div id='div_ft1_38' class="collapse in" align="left">
    <pre>
    
ft1_38: post请求body类型为： ,body内容为：{}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696621564, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_39' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_39</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_39' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_39'>失败</button>
    <div id='div_ft1_39' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_39' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_39'>失败</button>
    <div id='div_ft1_39' class="collapse in" align="left">
    <pre>
    
ft1_39: post请求body类型为： ,body内容为：{}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696622692, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_40' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_40</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_40' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_40'>失败</button>
    <div id='div_ft1_40' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_40' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_40'>失败</button>
    <div id='div_ft1_40' class="collapse in" align="left">
    <pre>
    
ft1_40: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696622956, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_41' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_41</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_41' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_41'>失败</button>
    <div id='div_ft1_41' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_41' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_41'>失败</button>
    <div id='div_ft1_41' class="collapse in" align="left">
    <pre>
    
ft1_41: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696623929, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_42' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_42</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_42' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_42'>失败</button>
    <div id='div_ft1_42' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_42' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_42'>失败</button>
    <div id='div_ft1_42' class="collapse in" align="left">
    <pre>
    
ft1_42: D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696625020, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_43' class='none'>
    <td class='failCase'><div class='testcase'>test_GHome_api_43</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_43' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_43'>失败</button>
    <div id='div_ft1_43' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_43' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_43'>失败</button>
    <div id='div_ft1_43' class="collapse in" align="left">
    <pre>
    
ft1_43: post请求body类型为： ,body内容为：{}
D:\worktool\python\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test-feiot.gosund.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
检查点-&gt;：http_code": 200, "err_code": 0, "success": true, "msg": ""
返回实际结果-&gt;：{"http_code": 401, "err_code": 10019, "success": false, "msg": "The login has expired. In order to protect the account security, the system requires you to log in again", "time": 1617696626031, "data": {}}
Traceback (most recent call last):
  File "C:\Users\jianghuaqiang\AppData\Roaming\Python\Python38\site-packages\ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "D:\project\Ghome_api\case\test_api.py", line 58, in test_GHome_api
    self.assertTrue(check in res_text)
AssertionError: False is not true


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>43</td>
    <td>0</td>
    <td>41</td>
    <td>2</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
